---
title: "Ukraine, the first 48 hours"
date: 2022-02-25T17:04:39Z
draft: false
tags: [ "ukraine", "russia", "war" ]
---

If you are unfamiliar with the geography of the area, see my previous post: [[{{< ref "famine-sword-fire.org" >}}][Famine, Sword, and Fire]]

As I said there, this is my attempt at a nonpartisan assembly and analysis of the events of the Russian Invasion of Ukraine, this post on the first forty-eight hours, as much for my own sake as anyone else's. Schelling points abound: Kiev/Kyiv, Dnieper/Dnipro, Chernigov/Chernihiv; my choice of spelling should not be taken to imply that I take any stance on geographical or political matters.

* What happened?
** Buildup
As early as March 2021, Putin began amassing troops in the area. Their number would fluctuate but on the 10th of February 2022, Russia and Belarus initiated ten days of joint military exercises[fn:allied-resolve] between 30k Russian troops and almost all (~50k) Belarusian forces. /Allied Resolve 2022/ was due to conclude on the 20th, but when the date came Russia announced the exercises would continue. On the 21st of February, Russia recognised the two breakaway republics and sent in 'peacekeeping' forces. Between Belarus, the people's republics, Crimea, and the Russian–Ukrainian border, Russia had gathered 150–200k personnel in the area surrounding Ukraine.
** Movements
[[https://upload.wikimedia.org/wikipedia/commons/4/4f/2022_Russian_invasion_of_Ukraine.svg]]
*** Commencement
At 2022/02/24 06:00 UTC+3, Putin announced that Russia was launching a 'special military operation' in Ukraine with the purpose to 'demilitarise and de-Nazify Ukraine', and put an end to the war in Donbas.
*** In the air
From 2022/02/24 03:00 GMT, 05:00 EET, air strikes occured nationwide, concentrating on air defences and military infrastructure. Russia achieved air superiority as was expected.
*** Donbas
Despite being the focus of the fighting for the past eight years, movement of the Donbas front has been minimal. It isn't clear if this is due to the large acculumation of Ukrainian forces before the invasion or that Russia have chosen to push on other fronts.

The largest Ukrainian-held city in this area is Mariupol, and a spearhead towards the city is the largest change of the front.
*** The Russian–Ukrainian border (Belgorod, Kharkiv)
The Russian–Ukrainian border was expected to be the main front of the attack, north of the major concentration of Ukrainian troops in the Donbas. The advance included a large number of armoured vehicles, taking large casualties without seizing Kharkiv. North of Kharkiv, however, Russian forces have surrounded the cities of Sumy and Konotop.
*** Crimea & Kherson
The isthmus joining Crimea to the Kherson Oblast is just 8km wide; just 8000 men could form a wall across it standing shoulder-to-shoulder. The possibility of a traditional attack seems ludicrous, perhaps requiring airbourne landings in the enemy's rear, and yet no such thing seems to have happened and this has been the most successful front of the invasion.

The Ukrainian coast, not including Crimea, was historically known as /Novorossiya/ ('New Russia'), so you might see this name used to refer to the /Mykolaiv/, /Kherson/, and /Zaporizhzhia/ Oblasts.
**** Westwards
The first afternoon Russia took *Nova Kakhovka*, location of the Kakhovka Hydroelectric Power Plant, and in the evening the *Antonovskiy Bridge*, downstream of the powerplant and  10 km upstream of Kherson proper. These are the two southernmost crossings of the Dnieper. 100 km from the Russian lines that morning, the southern entrance to West Ukraine had been captured.

50 km beyond Kherson is Mykolaiv, and there were reports on the first day of Russian tanks being seen on the outskirts of the city which seems unlikely. The Ukrainians were able to retake at least Antonovskiy Bridge only to lose it again on the 25th.
**** Eastwards
A second force headed east from Crimea, towards the city of Melitopol. As of the evening of the 25th there are reports that each side controls a portion of the city, or that Russian forces have surrounded it.

The objective for this front is likely to join with the Donbas front. There are reports that a naval landing has been attempted between Melitopol and Mariupol which would advance this objective.
*** Belarus & Kiev
The viability of a large attack from this direction was widely dismissed. The Pinsk/Pripyat marshes are known for being unsuited for a swift advance, and there are few roads if one wishes to avoid the marshes. Despite this, it has become possibly the most important theatre of the war.
**** The far west (Brest, Lutsk, Volyn)
There were some reports of an incursion of the Belarusian–Ukrainian border near to Poland. But these were mistaken[fn:wiki-mistake], as far as we can tell. There are reports that troops are now assembling at Brest, possibly to cut Ukraine off from Poland and the NATO materiel that comes across that border, but it remains to be seen.
**** East bank of the Dnieper
An advance of Russians across the Belarusian border was halted when it reached Chernihiv (Chernigov). Instead the Russians have bypassed Chernihiv, passing between it and the Dnieper.
**** West bank of the Dnieper
Early in the morning video was released showing a column of armoured vehicles entering Ukraine from the Vilcha checkpoint on the border with Belarus. Ukraine reported that their advance was halted, but later in the day troops took Pripyat, location of the Chernobyl Nuclear Power Plant, and the city Chernobyl to its south, continuing to Ivankiv, halfway to Kyiv.
**** Hostomel Airport (aka Antonov Airport)
Hostomel/Gostomel is a town to the northwest of Kyiv, 10 km from its extremeties and 20 km from its centre.

>30 Russian helicopters landed troops at the airport, hoping to create an airbridge to Kyiv. They were successful in gaining control of the airport but were soon attacked by the Ukrainian 4th Rapid Reaction Brigade.

Ukrainian reports suggest that the Russians were entirely destroyed, denied by the Russians. Following the success at Ivankiv, the Russians were reinforced from the north. Russia claims that 200 Ukrainians were killed whilst Russia lost none.
**** Kyiv
As Russian troops approach Kyiv from the north on the both the west and east banks of the Dnieper, small arms fire can be heard by residents. The Ukrainians have distributed thousands of automatic rifles to Kyiv's inhabitants, and anti-armour weapons have arrived in the city from NATO members.

There are reports that power plants are being hit, attack helicopters amassed in Belarus, and troops moving to encircle the city from the east and west. The capture of Kiev, and its government, must be Russia's primary objective. It seems that this city will be the focus of the next 48 hours.

The difficulty of moving across the marshes is probably the reason that Russia is flying troops into Kyiv, despite the danger. Ukraine's military have claimed that on the night of 2022/02/25 their air defence downed a Russian transport plane ferrying troops to the south of Kyiv.
*** Zmiinyi Island
In what has become one of the most famous moments of the war, the 13 Ukrainian soldiers stationed on Zmiinyi Island told the Black Sea flagship /Moskva/ to 'go fuck itself' ('Русский военный корабль, иди на хуй', 'Russky voyenny korabl, idi na khuy'). The 13 died to a man. Bizarrely, the Russians have provided a completely opposite claim: that the Ukrainians had 82 soldiers stationed on the small island, all of whom surrendered voluntarily.
** Ukrainian response
*** Mobilisation
On the morning of 2022/02/24, the Ukrainian President declared martial law, urging citizens to stay home:
#+BEGIN_QUOTE
Dear Ukrainian citizens, this morning President Putin announced a special military operation in Donbas. Russia conducted strikes on our military infrastructure and our border guards. There were blasts heard in many cities of Ukraine. We’re introducing martial law on the whole territory of our country. A minute ago I had a conversation with President Biden. The US have already started uniting international support. Today each of you should keep calm. Stay at home if you can. We are working. The army is working. The whole sector of defense and security is working.

No panic. We are strong. We are ready for everything. We will win over everybody because we are Ukraine.
#+END_QUOTE

In the afternoon, the head of customs in Lviv announced:
#+BEGIN_QUOTE
Men aged 18-60 will not be allowed to leave the country. Please do not panic and do not try to cross the border on your own! Victory is ours! Glory to Ukraine!
#+END_QUOTE

Shortly after 2022/02/24 23:00 UTC+2, President Zelensky announced a general mobilisation of Ukrainian males:
#+BEGIN_QUOTE
In connection with the military aggression of the Russian Federation against Ukraine and to ensure the defense of the state, maintaining combat and mobilization readiness of the Armed Forces of Ukraine and other military formations, on the basis of the proposal of the National Security and Defense Council of Ukraine. 1, 17, 20 of the first part of Article 106 of the Constitution of Ukraine, I decree: to announce and conduct a general mobilization.
#+END_QUOTE
Full text.[fn:mobilisation]

I cannot understand why it took 24 hours to announce a mobilisation, an eventuality that had surely been planned for.

During the course of the 25th, thousands of automatic rifles have been handed out freely, particularly to the inhabitants of Kyiv.

** Losses
*** *Russian*
**** per Russia
- 2 planes crashed
**** per Ukraine
- 2.8k killed
- ~80 tanks destroyed
- >500 vehicles detroyed
- 10 aircraft shot down
- 7 helicopters shot down
**** per UK
- 450 killed
*** *Ukrainian*
**** per Ukraine
- 40+ soldiers killed
- 2 aircraft shot down
**** per Russia
- all airbases and air defence neutralised
- 14 soldiers surrendered
- 4 aircraft shot down
- 1 helicopter shot down
- 4 drones shot down
**** per UK
- 137 killed
* Analysis
We must be humble when criticising, both sides have each been planning their actions here for eight years. When identifying missteps, there is a good chance we are wrong and analysing on the basis of insufficient evidence.

** Allied Resolve
It seems that the Allied Resolve military exercises with Belarus exercises were to assemble enough troops to allow for a capture Kyiv through the Pripyat marshes.

** Ukrainian response
The initial Ukrainian response seemed weak. The delayed conscription. The failure to hold the Crimean chokepoint. Allowing Russia to cross the Dnieper, Ukraine's greatest natural barrier, on the first day seemed to predict the a wholesale failure of Ukrainian defence.

Did Ukraine over commit to the east? Did Ukraine neglect the Crimean front? Did Ukraine not give credence to the possibility of invasion until too late?

All of those could be true. But perhaps, just maybe, much of this is to a Ukrainian plan (copium).
The sighting of Russian forces far deeper than they have any right being (Mykolaiv, Zaporizhzhia) suggest to me that Russian forces might be performing deep strikes into Ukrainian territory, think of Rommel's 7th Panzer Division during Fall Gelb, advancing far with little car for its rear because whatever it leaves behind will need to retreat. The /Soviet Deep Battle/ has been a mainstay of Russian military theory since before WWII. If the Ukrainians predicted this, what's the effective defence? To allow the enemy armour to penetrate and then close on the baggage trains that follow.

Maybe this can explain some of the losses at Vilcha, Chernigov, Kharkov. Maybe it's just copium.

** Russian performance
The UK MoD believes that Russia has likely not achieved her first-day expectations. Particularly, the loss of Hostomel Airport, if it ever was actually lost, must have been a blow to Russian confidence. Seizing an airport so close to Kyiv, and disabling any nearby air defence, would be a /coup de main/.
The losses around Kharkiv seem particularly heavy, and the advance on the second day seems unremarkable.

How can we understand this? Are these just probing attacks? UK intelligence suggests that Russia has committed just one third of the forces it assembled for the offensive. A new wave of troops might be moving in to exploit the fronts where they've seen most success, Kyiv and Kherson.

Does anything other than Kyiv really matter? The attacks in the east might not be intended to gain much land at all, but to keep Ukrainian troops there. Either take Kyiv and Ukraine falls, or take the Dnieper and eastern Ukraine is encircled.

** Predicted next steps
*** Russia
- take Kyiv
- control Dnieper
- link northern and southern fronts
- link Crimean and Donbas fronts
*** Ukraine
- mobilise 1M troops
- counterattacks to prevent resupply
- militia wage unconventional warfare in cities
* Next posts
- narratives and counternarratives
- what I got wrong in the build-up

[fn:allied-resolve]
[[https://www.reuters.com/world/europe/russia-belarus-extend-huge-military-exercises-belarus-ministry-2022-02-20/]]

[fn:wiki-mistake]
[[https://commons.wikimedia.org/wiki/File_talk:War_in_Ukraine_(2022)_en.png]]

[fn:mobilisation]
https://www.ukrinform.ua/rubric-ato/3412114-zelenskij-pidpisav-ukaz-pro-zagalnu-mobilizaciu.html :
#+BEGIN_QUOTE
In connection with the military aggression of the Russian Federation against Ukraine and to ensure the defense of the state, maintaining combat and mobilization readiness of the Armed Forces of Ukraine and other military formations, on the basis of the proposal of the National Security and Defense Council of Ukraine. 1, 17, 20 of the first part of Article 106 of the Constitution of Ukraine, I decree: to announce and conduct a general mobilization.

The mobilization will be carried out on the territory of Vinnytsia, Volyn, Dnipropetrovsk, Donetsk, Zhytomyr, Zakarpattia, Zaporizhia, Ivano-Frankivsk, Kyiv, Kirovohrad. Luhansk, Lviv, Mykolaiv, Odesa, Poltava, Rivne, Sumy, Ternopil, Kharkiv, Kherson, Khmelnytsky, Cherkasy, Chernivtsi, Chernihiv regions, the city of Kyiv.

The mobilization will be carried out within 90 days from the date of entry into force of this decree.

The decree also provides for the conscription of conscripts, reservists and vehicles to meet the needs of the Armed Forces, the National Guard, the Security Service of Ukraine, the State Border Guard Service, the State Special Transport Service, the State Service for Special Communications and Information Protection, and other military formations in Ukraine. volumes determined in accordance with the mobilization plans.

The General Staff of the Armed Forces of Ukraine has been instructed to determine the order and amounts of conscription of conscripts, reservists and vehicles of the national economy within the general mobilization period.

The Cabinet of Ministers should provide funding and take, within its authority, other measures related to the announcement and conduct of general mobilization.

In addition, the Security Service of Ukraine has been instructed to take counterintelligence measures during the general mobilization.

In turn, local executive bodies in cooperation with territorial centers of staffing and social support, with the participation of local governments and with the involvement of enterprises, institutions and organizations of all forms of ownership, individuals - entrepreneurs must organize and provide in the prescribed manner:

1) timely notification and arrival of citizens called up for military service, arrival of equipment at assembly points and military units;

2) conscription of conscripts, reservists for military service, their delivery to military units and institutions of the Armed Forces of Ukraine, the National Guard, the Security Service of Ukraine. State Border Guard Service, State Special Transport Service, State Service for Special Communications and Information Protection of Ukraine, other military formations of Ukraine;

3) temporary allocation of buildings, structures, land, transport and other material and technical means, provision of services to the Armed Forces of Ukraine, the National Guard of Ukraine, the Security Service of Ukraine, the State Border Guard Service of Ukraine, the State Special Transport Service, the State Special Communications Service and protection of information of Ukraine and other military formations of Ukraine in accordance with mobilization plans.

Also, the heads of regional state administrations to ensure the establishment and operation of regional, district and city medical commissions.
#+END_QUOTE
