---
title: "Famine, Sword, and Fire"
date: 2022-02-25T02:06:17Z
draft: false
tags: [ "ukraine", "russia", "war" ]
---

Next post: [[{{< ref "2022-02-24.org" >}}][Ukraine, the first 48 hours]]

In a few articles I will attempt to provide some data and analysis on the [[https://en.wikipedia.org/wiki/2022_Russian_invasion_of_Ukraine][ongoing conflict in Ukraine]].

In this first post I provide the required politico-economic and geographic knowledge needed to parse the news coming out of Ukraine.

Subsequent posts will attempt to document the military actions that took place, analyse them, and analyse the greater conflict: its causes, effects, and interpretations.

Disclaimer: Whilst I am broadly sympathetic to the position of the British government, I am consciously attempting to be non-partisan. The spelling choices I make are just those I am familiar with and do not represent me taking a position on geographical or political claims.

* [[https://en.wikipedia.org/wiki/Ukraine][Ukraine]]
Population inc. disputed territory: 43.4M \\
Population exc. disputed territory: 37.3M \\
Area: 2.5 UKs \\
GDP: $204B, $5k/capita
** [[https://en.wikipedia.org/wiki/Armed_Forces_of_Ukraine][Armed Forces of Ukraine]]
245k active troops, 220k reservists (as of 2022/02/23). \\
7M fit for service.
* Disputed territories
Jointly, the Donetsk and Luhansk Oblasts are known as /Donbas/, a portmanteau of /Donets basin/.
** [[https://en.wikipedia.org/wiki/Donetsk_People%27s_Republic][Donetsk People's Republic (DPR/DNR)]]
Population 2.3M, area: 3% of UK, 1/3 of entire Oblast.
** [[https://en.wikipedia.org/wiki/Luhansk_People%27s_Republic][Luhansk People's Republic (LPR/LNR)]]
Population 1.5M, area: 3% of UK, 1/3 of entire Oblast.
** [[https://en.wikipedia.org/wiki/Crimea][Crimean peninsula]]
Governed by the [[https://en.wikipedia.org/wiki/Autonomous_Republic_of_Crimea][Autonomous Republic of Crimea]] and [[https://en.wikipedia.org/wiki/Sevastopol][Sevastopol]].
Population: 2.4M, area: 10% of UK.
* [[https://en.wikipedia.org/wiki/Russian_Armed_Forces][Russia]]
Population exc. disputed territory: 143M, area: 70 UKs. \\
GDP: $1.7T, $12k/capita.
** [[https://en.wikipedia.org/wiki/Russian_Armed_Forces][Russian Armed Forces]]
1M active troops, 2M reservists. \\
The Russians spend ~4% of all GDP on the military, 11th in the world, Israel is the only Western nation higher at 5.3%.
* [[https://en.wikipedia.org/wiki/Belarus][Belarus]]
Population: 9.3M, area: 0.75 UKs. \\
GDP: $58B, $6k/capita
** [[https://en.wikipedia.org/wiki/Armed_Forces_of_Belarus][Belarusian Armed Forces]]
62k active troops, 350k reservists.
* Geography
** Forest vs steppe
Ukraine can be divided into the forested north-west and the south-east is a steppe, a region of grassland plains. The north-west is almost entirely Ukrainian-speaking, the south-west a mix of Ukrainian- and Russian-speaking populations.
** Dnieper
Runs north to south, dividing the country in twain, through Kyiv, Cherkasy, Dnipro, Zaporizhzhia, Kherson, into the Black Sea. Apart from the forest–steppe division, it is the greatest feature of the Ukrainian landscape.
** Bordering countries
Moldova and Romania in the south-west.
Small borders in the west with Hungary and Slovakia.
A larger western border with Poland.
To the north is Belarus.
Longest border is with Russia in the east.
** Pinsk marshes
Also known as the Pripyat marshes, they are famous for [[https://en.wikipedia.org/wiki/Pinsk_Marshes#Second_World_War][their role in WWII]].
The marshes surround the Pripyat river, which runs east roughly along the Ukrainian–Belarusian border, and drains into the Dnieper in Ukraine's north.
** Black Sea
Ukraine's southern neighbour. Entrance and exit controlled by Turkey.
** Sea of Azov
Separated from the Black Sea by the Crimean peninsula, connected to the Black Sea by the Kerch Strait.
** Crimea
A peninsula connected to the mainland by the Isthmus of Perekop. And seperated from southern Russia by the Kerch strait.
** Cities
I have included some smaller cities because of their relevance to
- Kyiv :: 3.0M, north, 100 km from Belarus
- Kharkiv :: 1.4M, east, 30 km from Russia
- Odesa :: 1.0M, south-west, on the coast
- Dnipro :: 980k, east, on Dnieper
- Donetsk :: 905k, east, capital of the DPR
- Zaporizhzhia :: 722k, east, on Dnieper
- Lviv :: 720k, west, 50 km from Poland
- Sevastopol :: 464k, south, Crimean peninsula
- Mariupol :: 431k, east, 20 km from the DPR, on the coast
- Luhansk :: 400k, east, just north of Donetsk, capital of LPR
- Kherson :: 283k, south, 100 km north-west of Crimea

* Title
[[https://shakespeare.folger.edu/shakespeares-works/henry-v/prologue/][Henry V: Prologue]]
